added firebase app distribution

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -63,3 +63,16 @@ workflows:
       email:
         recipients:
           - jpascasio1993@gmail.com
+      scripts:
+          - |
+            #!/usr/bin/env sh
+            set -e   # exit on first failed command
+            set -x   # print all executed commands to the log
+
+            if [[ -f "$FCI_BUILD_OUTPUT_DIR/app-qa-release-universal.apk" ]]
+            then
+              # Android Firebase App Distribution CLI
+              firebase appdistribution:distribute $FCI_BUILD_OUTPUT_DIR/app-release-universal.apk --app \
+              1:1042396097004:android:ad9660081d7c53df --groups "ripeconcepts-qa-testers" \
+              --token "$FIREBASE_TOKEN"
+            fi
